name: Release NuGet
on:
  release: 
    types: [published]
        
jobs:
  release:
    name: Release NuGet
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - run: echo '### Release ${{ inputs.version }}' >> $GITHUB_STEP_SUMMARY
      - run: dotnet restore
      - run: dotnet pack -c Release -o build -p:Version=$(echo "${{ github.ref_name }}" | sed 's/v//' ) src/MonoMac.csproj
      - run: dotnet nuget push build/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json  
